services:

  db:
    image: postgres:13
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres

  nest-app:
    image: nest-cloud-run
    restart: always
    ports:
      - 3000:3000